### ISSUE TITLE
HelloWorld does not build automatically when you start it from VS

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#42]
When you download HelloWorld from GitHub, open in VS and press debug, there is a message saying that the binary file is not found.

This is because the solution is not configured to automatically build when debugging.

I have a fix locally and can submit it.

cc @Mackiovello

**Comment by ErlendLandro** [comment]
What is the fix?

Does it require significant changes in the tutorial?

Why does this problem occur?

**Comment by warpech** [comment]
The problem occurs because the "Build" checkbox is not selected in Solution > Properties > Configuration in Visual Studio. I don't know why this happens, but it happens sometimes.

I don't know if I will manage to do the rebase this week. If you have some time, maybe you could fix it?

**Comment by ErlendLandro** [comment]
I'll take care of it tomorrow

**Comment by ErlendLandro** [comment]
Okay, so this did not turn out the way I expected.

This is what I did:
1. Clone repository
    * Checkboxes are not selected
2. Run `git checkout -b tutorial-20161222`
    * Checkboxes are not selected
3. Run `git rebase --interactive --root`
    * Checkboxes are now suddenly selected on all commits
4. Run ` git push --set-upstream origin tutorial-20161222`
5. Delete local repo
6. Clone remote repository
7. Run `git checkout tutorial-20161222`
8. Start app from VS and hit same error

I'm not sure what I'm doing wrong. It seems like doing a rebase modifies the configuration, though that doesn't make much sense. If you know where I went wrong, that would be great. Otherwise, I'll keep trying.

**Comment by warpech** [comment]
I think we can use the Git history on the sln file to tell us what's going on.

The history of the sln file shows that it was changed only in two steps: https://github.com/StarcounterSamples/HelloWorld/commits/3ba2731f8333160dcb08be32365ea9e01ba357f9/HelloWorld.sln

`git checkout 3ba2731f8333160dcb08be32365ea9e01ba357f9` > Visual Studio has no checkboxes checked.

`git checkout 7ce6176d25ed9127862602b7a1497b8f8d8785d1` > Visual Studio has all (one) checkbox checked.

Can you try fixing it in Step 8?

**Comment by warpech** [comment]
Try to delete the `.vs` directory between the steps. Maybe this interferes.

**Comment by ErlendLandro** [comment]
You're a genius! It's fixed now, closing the issue.
